notes:
  - 这个文件是打包后的代码，源代码在 repo 里 qwq~
  - "Github Repo => https://github.com/memset0/lavandula"
tampermonkey:
  name: lavandula
  description: memset0 的 Toy Project 整合包（雾
  version: 1.1.1
  author: memset0
  namespace: lavandula
  match:
    - https://blog.csdn.net/*
    - https://www.cnblogs.com/*
    - https://www.zybuluo.com/*
    - https://*.github.io/*
    - https://www.luogu.com.cn/problem/*
    - https://vjudge.net/problem/*
    - http://uoj.ac/problem/*
    - https://uoj.ac/problem/*
    - https://loj.ac/problem/*
    - https://duck.ac/problem/*
    - https://floj.tech/problem/*
    - https://codeforces.com/contest/*
    - https://codeforces.com/gym/*
  require:
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/jquery.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/lodash.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/highlight.min.js
  grant: none