tampermonkey:
  name: lavandula
  description: 咕咕咕
  version: 1.0.0
  author: memset0
  namespace: lavandula
  match:
    - https://blog.csdn.net/*
    - https://yhx-12243.github.io/*
  require:
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/jquery.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/lodash.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/highlight.min.js
  grant: none