notes:
  - 这个文件是打包后的代码，源代码在 repo 里 qwq~
  - "Github Repo => https://github.com/memset0/lavandula"
tampermonkey:
  name: lavandula
  author: memset0
  description: memset0 的 Toy Project 整合包（雾
  namespace: lavandula
  match:
    - https://blog.csdn.net/*
    - https://www.cnblogs.com/*
    - https://www.zybuluo.com/*
    - https://*.github.io/*
    - https://www.luogu.com.cn/problem/*
    - https://vjudge.net/problem/*
    - http://uoj.ac/problem/*
    - https://uoj.ac/problem/*
    - https://loj.ac/problem/*
    - https://duck.ac/problem/*
    - https://floj.tech/problem/*
    - https://codeforces.com/problemset/*
    - https://codeforces.com/contest/*
    - https://codeforces.com/gym/*
    - https://codeforces.ml/problemset/*
    - https://codeforces.ml/contest/*
    - https://codeforces.ml/gym/*
    - https://codeforc.es/problemset/*
    - https://codeforc.es/contest/*
    - https://codeforc.es/gym/*
  require:
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/jquery.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/lodash.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/low.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/highlight.min.js
    - https://cdn.jsdelivr.net/gh/memset0/lowdb-adapter-greasemonkey/GreasemonkeyAsync.js
  resource:
    - mdui-css https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/mdui/mdui.min.css
    - mdui-js https://cdn.jsdelivr.net/gh/memset0/lavandula/lib/mdui/mdui.min.js
  grant:
    - unsafeWindow
    - GM.setValue
    - GM.getValue
    - GM.listValue
    - GM.deleteValue
    - GM_addStyle
    - GM_getResourceText